### ISSUE TITLE
In nested packages, what are the offsets relative to?

### ISSUE THREAD

**Issue by lrosenthol** [dimich-g/webpackage#17]
It's not clear from the document whether offsets specified in the header or index of a nested package are to be taken from the start of the containing/primary package data or from the start of the nested package header.

**Comment by bmeck** [comment]
for streaming purposes I would hope it is relative to the nested package and not the outer package.

**Comment by lrosenthol** [comment]
@bmeck I would hope so too - but the spec is silent on the topic...

**Comment by dimich-g** [comment]
Commit https://github.com/dimich-g/webpackage/commit/45bf2223ef53764c5b42ae614744267aa7fe90ed
added the note about relative offsets - the offsets inside the nested package are relative to the nested package. The idea is that the nested packages are full-formed on their own and can be created/signed separately, then included as-is into containing package.
