### ISSUE TITLE
Self Extracting Binaries

### ISSUE THREAD

**Issue by bmeck** [dimich-g/webpackage#20]
For self extracting executables, the common implementation is to produce a file which is a concatenated binary executable head, and an archive tail.

Node and Electron are looking at reusing webpackage possibly as things progress and need a way:

* Have a signature for the concatenated binary+archive
* Have a length pointer to let the runtime jump to the start of the archive

Self extracting zip files, ASAR from electron, and NODA are examples of this from the past. These all work by having a directory at end of file, but for all use cases I know a pointer to start of archive on the tail would be sufficient. Doing so would most likely just be a series of magic bytes and kength that exists at the end of the file. It could be optional but must be easy to add to an existing webpackage.

For a signature of the entire binary + archive this is important so people don't perform a secondary concatenation and load a different archive than expected, it most likely can just be a well known header that optionally exists on the package headers.

**Comment by mrdewitt** [comment]
Seems that the most important incompatibility here is that an archive with an executable at the head won't be readable by archive readers since we use header lines to define the content type, signature, etc.  

Signature of the binary+archive seems like a less important feature, unless the OS is going to know how to validate the binary signature before it executes it. Is there a use case I'm not seeing?  Can we split the discussion of binary signatures from the more general self-extracting case?

**Comment by bmeck** [comment]
I would not expect to keep the same file extension if it is self extracting. Unsure what workflow:

> Seems that the most important incompatibility here is that an archive with an executable at the head won't be readable by archive readers since we use header lines to define the content type, signature, etc.

Would conflict with.

Signing of a binary+archive is important if the runtime wants to prevent certain types of concatenation attacks. Otherwise:

```sh
> cat runtime webpackage > extracting_bin
```

could have the package replaced by doing

```sh
> cat extracting_bin other_webpackage
```

Which would not be good if you are trying to distribute a binary.

Signing tools like `codesign` or `toolsign` are currently outside my intents but I don't see any problem with using them ontop in conjunction with a signature method for the combined executable.

**Comment by lrosenthol** [comment]
Shouldn't signign the binary+archive be something that the self-extracting
executable has to worry about and not something we need to worry about?  If
they want to use our packaging format (by cat'ing it to the end of
themselves), then they are responsible for their own signing - be it
standard/OS code sign or something else.

**Comment by bmeck** [comment]
@lrosenthol mostly yes, but as was talked about a bit ago on a call, there needs to be a standard so that the differing runtimes can leverage the same process/tooling to generate these. Same reason to have a trailer that could be picked up to find the beginning of the archive.

**Comment by lrosenthol** [comment]
@bmeck I don't actually believe that a standard is needed in this case. And if there is, wouldn't it be better to come from the folks doing the SEA's and tooling for same, rather than us?  Do we have any folks from those communities participating here?

**Comment by bmeck** [comment]
Runtime people interested in this: Me (Node), @jasnell (Node), and @groundwater (Electron)

**Comment by jyasskin** [comment]
#36 added a length to the end of the package: https://github.com/dimich-g/webpackage#overall-format. Is that sufficient?

**Comment by bmeck** [comment]
@jyasskin yes

**Comment by Jxck** [comment]
@bmeck adding the length *inside cbor format* also works fine for your use case ?

```
> cat extracting_bin other_webpackage
```

it seems necessary decoding/re-encoding cbor format when adding other package to current .wbn .

**Comment by bmeck** [comment]
Only works if the position is known, which means it must not be an unordered named field, it would still need to be at the very end of the payload. Is that what you are suggesting? E.g.

```
{
  size,
  payload
} | {
  payload,
  size
}
```

wouldn't work

```
[
  payload,
  size // guaranteed location at tail of the whole bundle
]
```

is probably ok

**Comment by jyasskin** [comment]
CBOR integers are variable-sized and can't be parsed backwards, so the total size does need to be a byte-string like it's currently specified: https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#name-top-level-structure. They are inside the overall CBOR format, which is easy since an array's last item is also the last bytes of the encoding of the array.

**Comment by Jxck** [comment]
adding another package to current webbundle should update section and section-length too.
you can update only length without parsing whole cbor. but updating section/section-length need to parse whole cbor isn't it ?
in that case, move only length to bottom of cbor array will help this case ?
