### ISSUE TITLE
application/index not defined as a valid media type

### ISSUE THREAD

**Issue by lrosenthol** [dimich-g/webpackage#9]
As defined [in its IANA registration](https://www.iana.org/assignments/media-types/application/index), this is not a valid media type.  Instead, either a new sub-type should be defined and/or the appropriate format extension (eg. +json) should be added.

**Comment by bmeck** [comment]
I would vote for a different sub-type, `index` doesn't really make me think that the content is also included. This also doesn't appear to match up with any of https://tools.ietf.org/html/rfc2652 or the subtree:

```
application/index.cmd
application/index.response
application/index.obj
application/index.vnd
```
